title: Muhammad Adib Bin Ahmad # your name (or website title) here
logo: "/images/deep_2020.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Muhammad Adib Ahmad born 1983 is an accomplished programmer, software engineer and Assistant IT Manager of Kiswire SEA, a global wire manufacturing company headquartered in Busan, Korea. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
